export { default as HeaderSection } from './HeaderSection/HeaderSection';
export { default as HomeSection } from './HomeSection/HomeSection';
export { default as AboutSection } from './AboutSection/AboutSection';
export { default as MenuSection } from './MenuSection/MenuSection';
export { default as ProductsSection } from './ProductsSection/ProductsSection';
export { default as ReviewSection } from './ReviewSection/ReviewSection';
export { default as ContactSection } from './ContactSection/ContactSection';
export { default as BlogsSection } from './BlogsSection/BlogsSection';
export { default as FooterSection } from './FooterSection/FooterSection';
